#!/bin/sh
# Run the autotools bootstrap sequence to create the configure script

# Abort execution on error
set -e

if which libtoolize > /dev/null; then
    libtoolize="libtoolize"
elif which glibtoolize >/dev/null; then
    libtoolize="glibtoolize"
else
    echo "$0: Error: libtool is required" >&2
    exit 1
fi

# bootstrap the autotools
(
set -x
aclocal
${libtoolize} --automake --copy
autoconf
autoheader
automake --gnu --add-missing --copy
)

echo "Bootstrap complete. Quick build instructions:"
echo "./configure ...."
